GET http://localhost:5000/tinder/cards

###

POST http://localhost:5000/tinder/cards
Content-Type: application/json

{
"name": "Eva Marcille",
"imgURL": "https://img.srgcdn.com/e//M3QwdEtiTE1GNW1VYlBid0p4T3QuanBn.jpg"
}


###

POST http://localhost:5000/tinder/cards
Content-Type: application/json

{
"name": "Eva Marcille",
"imgURL": "https://img.srgcdn.com/e//M3QwdEtiTE1GNW1VYlBid0p4T3QuanBn.jpg"
{
